### PR TITLE
Implemented other functions from git-repo-info

### PR DESCRIPTION
**Pull request by IAmJulianAcosta**
I'm just implementing other functions from `git-repo-info` to make them available in `ember`.

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks!

**Comment by IAmJulianAcosta** [comment]
@rwjblue could you please release the changes? :D

**Comment by kellyselden** [comment]
@rwjblue friendly ping

**Comment by kellyselden** [comment]
@IAmJulianAcosta It was release.

**Pull request merged**
